# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(918, 747)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(190, 150, 470, 470))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(0)

        self.clockLine = QtWidgets.QLineEdit(self.centralwidget)
        self.clockLine.setGeometry(QtCore.QRect(480, 100, 61, 41))
        self.clockLine.setAutoFillBackground(False)
        self.clockLine.setFrame(False)
        self.clockLine.setReadOnly(True)
        self.clockLine.setObjectName("clockLine")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(190, 100, 281, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_white = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_white.setObjectName("pushButton_white")
        self.pushButton_white.setObjectName("white")
        self.pushButton_white.setStyleSheet("background-color: white")
        self.horizontalLayout.addWidget(self.pushButton_white)
        self.pushButton_black = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.horizontalLayout.addWidget(self.pushButton_black)
        self.pushButton_black.setStyleSheet("background-color: black")
        self.pushButton_black.setObjectName("black")
        self.pushButton_red = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_red.setStyleSheet("background-color: red")
        self.horizontalLayout.addWidget(self.pushButton_red)
        self.pushButton_red.setObjectName("red")
        self.pushButton_green = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.horizontalLayout.addWidget(self.pushButton_green)
        self.pushButton_green.setStyleSheet("background-color: green")
        self.pushButton_green.setObjectName("green")
        self.pushButton_blue = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.horizontalLayout.addWidget(self.pushButton_blue)
        self.pushButton_blue.setStyleSheet("background-color: blue")
        self.pushButton_blue.setObjectName("blue")
        self.pushButton_yellow = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.horizontalLayout.addWidget(self.pushButton_yellow)
        self.pushButton_yellow.setStyleSheet("background-color: yellow")
        self.pushButton_yellow.setObjectName("yellow")
        self.pushButton_purple = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.horizontalLayout.addWidget(self.pushButton_purple)
        self.pushButton_purple.setStyleSheet("background-color: purple")
        self.pushButton_purple.setObjectName("purple")

        self.nicknameLine = QtWidgets.QLineEdit(self.centralwidget)
        self.nicknameLine.setGeometry(QtCore.QRect(550, 100, 111, 41))
        self.nicknameLine.setFrame(False)
        self.nicknameLine.setReadOnly(True)
        self.nicknameLine.setObjectName("nicknameLine")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 918, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
